package events

const INPUT_MOUSE_CLICK = "INPUT_MOUSE_CLICK"
const INPUT_MOUSE_CLICK_UP = "INPUT_MOUSE_CLICK_UP"
const INPUT_MOUSE_CLICK_DOWN = "INPUT_MOUSE_CLICK_DOWN"
const INPUT_MOUSE_MOVE = "INPUT_MOUSE_MOVE"
const INPUT_MOUSE_WHEEL = "INPUT_MOUSE_WHEEL"
